const data = [
    {
        id:"1",
        title:"Samsun Atakum Sahilde Daire",
        explain:"Deniz manzaralı, tramvaya yürüme mesafesi(koşarak 10 dk)",
        price:"111 ",
        image:" ",
        phone:" ",
        city:"Samsun",
        status:" ",
        meters:" ",
        rooms:" ",
        floor:" ",
        furniture:" ", 
    },
    {
        id:"2",
        title:"Ev İlanı",
        explain:" ",
        price:"222 ",
        image:" ",
        phone:" ",
        city:"Ankara",
        status:" ",
        meters:" ",
        rooms:" ",
        floor:" ",
        furniture:" ", 
    },
    {
        id:"3",
        title:"Ev İlanı",
        explain:" ",
        price:"333 ",
        image:" ",
        phone:" ",
        city:"Samsun",
        status:" ",
        meters:" ",
        rooms:" ",
        floor:" ",
        furniture:" ", 
    },
    {
        id:"4",
        title:"Ev İlanı",
        explain:" ",
        price:"444 ",
        image:" ",
        phone:" ",
        city:"İstanbul",
        status:" ",
        meters:" ",
        rooms:" ",
        floor:" ",
        furniture:" ", 
    },
    {
        id:"5",
        title:"Ev İlanı",
        explain:" ",
        price:"555 ",
        image:" ",
        phone:" ",
        city:"Adana",
        status:" ",
        meters:" ",
        rooms:" ",
        floor:" ",
        furniture:" ", 
    },


]

module.exports = data;